name: Exécuter un script JavaScript

on: [push]

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v3

      - name: Exécuter le script JavaScript
        run: node index.js
